source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

gem 'cancancan', '~> 1.15'
# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

gem 'bootstrap', '~> 4.6.0'

gem 'faker'

gem 'selectize-rails'

gem 'active_model_serializers'

gem 'rack-cors'

gem 'omniauth-github', '~> 1.4'

gem 'geocoder'
gem 'gmaps4rails'
gem 'underscore-rails'
gem 'stripe'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails' #libary heavily integrated into rails to allow us to test stuff really easily
  gem 'factory_bot_rails'
  gem 'rails-controller-testing'
  
end

# the gemfile is where all your modules are listed
# they are seperated into different environments
# once you add some other gems, you have to run `bundle` inside ur terminal to install it

# Major.Minor.Patch
# gem 'cowsay', '>= 4.1.0' 
# means when you run `bundle` rails can install the version > or = version 4.1.0
# gem 'cowsay', '4.1.0'
# means I just want to install this version
# gem 'cowsay', '~> 4.1.0'
# install the version which is less than 5.0.0

# You can use command `rails c` to enter a `rails console` in your rails project
# Simmilar with pry or irb, it's opening a CLI you can type ruby code inside
# but inside here, you can also use gems installed for this project

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'
  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  # gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'cowsay', '~> 0.3.0'
  gem 'letter_opener'
  gem 'delayed_job_active_record'
  gem 'delayed_job_web'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
