class WelcomeController < ApplicationController
    # this file was generated by running the command:
    # rails g controller welcome
    
    # insied of controller every instance method is called an action
    def index
        # by default rails will render a template within
        # views/welcome folder, this welcome is the controller name
        # this action will render out the file views/welcome/index.html.erb
    end

    def goodbye
        
    end
    
    def form_example
        
    end
    
end
